- name: Configuring host_name
  ansible.builtin.shell: set-hostname {{ component }} - {{ env }}

- name: Installing nginx and using in frontend
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: copying nginx proxy file
  ansible.builtin.template:
    src: expense.conf
    dest: "{{ proxy_path }}"

# Importing a specific task from common role
- name: Run tasks/other.yaml instead of 'main'
  ansible.builtin.import_role:
    name: common
    tasks_from: pre-req

- name: Restarting {{ component }} service
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes