- name: Configuring hostname
  ansible.builtin.shell: set-hostname {{ component }}-{{ env }}

- name: Installing hvac , a pre-requisite for vault
  ansible.builtin.pip:
    name: hvac
    executable: pip3.11 

- name: Configuring node exporter
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node_exporter